In [132]:
from pandas2arff import *
import numpy as np
import pandas as pd

In [169]:
movies = pd.read_csv("movies.csv")
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [170]:
ratings = pd.read_csv("ratings.csv")
ratings.head()

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [171]:
total_votes = {}
total_ratings = {}

for index, row in ratings.iterrows():
    movieId = int(row.movieId)
    rating = float(row.rating)
    
    if movieId not in total_ratings:
        total_ratings[movieId] = 0
        total_votes[movieId] = 0
    
    total_ratings[movieId] += rating
    total_votes[movieId] += 1

In [172]:
def get_rating(row):
    movieId = row.movieId
    if movieId in total_ratings:
        row.rating = total_ratings[movieId] / total_votes[movieId]
    return row

movies["rating"] = 0
movies = movies.apply(get_rating, axis=1)

In [173]:
del movies["movieId"]
del movies["genres"]

In [174]:
movies

                                                  title    rating
0                                      Toy Story (1995)  3.872470
1                                        Jumanji (1995)  3.401869
2                               Grumpier Old Men (1995)  3.161017
3                              Waiting to Exhale (1995)  2.384615
4                    Father of the Bride Part II (1995)  3.267857
5                                           Heat (1995)  3.884615
6                                        Sabrina (1995)  3.283019
7                                   Tom and Huck (1995)  3.800000
8                                   Sudden Death (1995)  3.150000
9                                      GoldenEye (1995)  3.450820
10                       American President, The (1995)  3.689024
11                   Dracula: Dead and Loving It (1995)  2.861111
12                                         Balto (1995)  3.937500
13                                         Nixon (1995)  3.451613
14                              Cutthroat Island (1995)  2.318182
15                                        Casino (1995)  3.948864
16                         Sense and Sensibility (1995)  3.924419
17                                    Four Rooms (1995)  3.288462
18                Ace Ventura: When Nature Calls (1995)  2.597826
19                                   Money Train (1995)  2.538462
20                                    Get Shorty (1995)  3.536842
21                                       Copycat (1995)  3.355263
22                                     Assassins (1995)  3.090909
23                                        Powder (1995)  3.044118
24                             Leaving Las Vegas (1995)  3.742574
25                                       Othello (1995)  4.100000
26                                  Now and Then (1995)  3.142857
27                                    Persuasion (1995)  4.083333
28    City of Lost Children, The (Cité des enfants p...  4.025000
29    Shanghai Triad (Yao a yao yao dao waipo qiao) ...  4.050000
...                                                 ...       ...
9095  Teenage Mutant Ninja Turtles: Out of the Shado...  2.000000
9096          Popstar: Never Stop Never Stopping (2016)  1.000000
9097                             The Conjuring 2 (2016)  3.750000
9098                     Approaching the Unknown (2016)  0.500000
9099                                Ghostbusters (2016)  1.000000
9100                        Central Intelligence (2016)  2.500000
9101                                Jason Bourne (2016)  4.250000
9102                             The Maid's Room (2014)  1.500000
9103                        The Legend of Tarzan (2016)  2.500000
9104                    The Purge: Election Year (2016)  2.000000
9105              Mike & Dave Need Wedding Dates (2016)  4.000000
9106                         Survive and Advance (2013)  5.000000
9107                                    Tallulah (2016)  3.500000
9108                                       Piper (2016)  4.000000
9109                                       Nerve (2016)  0.000000
9110                       My Friend Rockefeller (2015)  2.500000
9111                                   Sunspring (2016)  0.500000
9112                  Author: The JT LeRoy Story (2016)  0.000000
9113                          Hell or High Water (2016)  0.000000
9114               Kingsglaive: Final Fantasy XV (2016)  3.000000
9115                                        Body (2015)  1.000000
9116                Sharknado 4: The 4th Awakens (2016)  1.500000
9117              The Last Brickmaker in America (2001)  5.000000
9118                                    Stranger Things  4.500000
9119                                      Rustom (2016)  5.000000
9120                                Mohenjo Daro (2016)  3.000000
9121                               Shin Godzilla (2016)  0.000000
9122  The Beatles: Eight Days a Week - The Touring Y...  5.000000
9123                           The Gay Desperado (1936)  0.000000
9124                              Women of '69, Unboxed  0.000000

[9125 rows x 2 columns]

In [175]:
user_movies = movies.copy()
user_movies["rating"] = 0
user_movies
# movies

                                                  title  rating
0                                      Toy Story (1995)       0
1                                        Jumanji (1995)       0
2                               Grumpier Old Men (1995)       0
3                              Waiting to Exhale (1995)       0
4                    Father of the Bride Part II (1995)       0
5                                           Heat (1995)       0
6                                        Sabrina (1995)       0
7                                   Tom and Huck (1995)       0
8                                   Sudden Death (1995)       0
9                                      GoldenEye (1995)       0
10                       American President, The (1995)       0
11                   Dracula: Dead and Loving It (1995)       0
12                                         Balto (1995)       0
13                                         Nixon (1995)       0
14                              Cutthroat Island (1995)       0
15                                        Casino (1995)       0
16                         Sense and Sensibility (1995)       0
17                                    Four Rooms (1995)       0
18                Ace Ventura: When Nature Calls (1995)       0
19                                   Money Train (1995)       0
20                                    Get Shorty (1995)       0
21                                       Copycat (1995)       0
22                                     Assassins (1995)       0
23                                        Powder (1995)       0
24                             Leaving Las Vegas (1995)       0
25                                       Othello (1995)       0
26                                  Now and Then (1995)       0
27                                    Persuasion (1995)       0
28    City of Lost Children, The (Cité des enfants p...       0
29    Shanghai Triad (Yao a yao yao dao waipo qiao) ...       0
...                                                 ...     ...
9095  Teenage Mutant Ninja Turtles: Out of the Shado...       0
9096          Popstar: Never Stop Never Stopping (2016)       0
9097                             The Conjuring 2 (2016)       0
9098                     Approaching the Unknown (2016)       0
9099                                Ghostbusters (2016)       0
9100                        Central Intelligence (2016)       0
9101                                Jason Bourne (2016)       0
9102                             The Maid's Room (2014)       0
9103                        The Legend of Tarzan (2016)       0
9104                    The Purge: Election Year (2016)       0
9105              Mike & Dave Need Wedding Dates (2016)       0
9106                         Survive and Advance (2013)       0
9107                                    Tallulah (2016)       0
9108                                       Piper (2016)       0
9109                                       Nerve (2016)       0
9110                       My Friend Rockefeller (2015)       0
9111                                   Sunspring (2016)       0
9112                  Author: The JT LeRoy Story (2016)       0
9113                          Hell or High Water (2016)       0
9114               Kingsglaive: Final Fantasy XV (2016)       0
9115                                        Body (2015)       0
9116                Sharknado 4: The 4th Awakens (2016)       0
9117              The Last Brickmaker in America (2001)       0
9118                                    Stranger Things       0
9119                                      Rustom (2016)       0
9120                                Mohenjo Daro (2016)       0
9121                               Shin Godzilla (2016)       0
9122  The Beatles: Eight Days a Week - The Touring Y...       0
9123                           The Gay Desperado (1936)       0
9124                              Women of '69, Unboxed       0

[9125 rows x 2 columns]

In [176]:
user_movies.loc[user_movies["title"].str.contains("Shawshank Redemption")]

                                title  rating
284  Shawshank Redemption, The (1994)       0

In [177]:
user_movies.loc[user_movies["title"].str.contains("Shawshank Redemption"), "rating"] = 5

In [178]:
user_movies.loc[user_movies["title"].str.contains("Shawshank Redemption")]

                                title  rating
284  Shawshank Redemption, The (1994)       5

In [179]:
user_movies.loc[user_movies["title"].str.contains("Forrest Gump")]

                   title  rating
321  Forrest Gump (1994)       0

In [180]:
user_movies.loc[user_movies["title"].str.contains("Godfather, The (1972)"), "rating"] = 4
user_movies.loc[user_movies["title"].str.contains("Godfather: Part II"), "rating"] = 2.5
user_movies.loc[user_movies["title"].str.contains("Pulp Fiction"), "rating"] = 3.5
user_movies.loc[user_movies["title"].str.contains("Oldboy"), "rating"] = 4
user_movies.loc[user_movies["title"].str.contains("Forrest Gump"), "rating"] = 4.5

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel/__main__.py:1: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  if __name__ == '__main__':

In [220]:
movies_transposed = movies.transpose()
user_movies_transposed = user_movies.transpose()

In [222]:
movies_transposed

,0,1,2,3,4,5,6,7,8,9,...,9115,9116,9117,9118,9119,9120,9121,9122,9123,9124
title,Toy Story (1995),Jumanji (1995),Grumpier Old Men (1995),Waiting to Exhale (1995),Father of the Bride Part II (1995),Heat (1995),Sabrina (1995),Tom and Huck (1995),Sudden Death (1995),GoldenEye (1995),...,Body (2015),Sharknado 4: The 4th Awakens (2016),The Last Brickmaker in America (2001),Stranger Things,Rustom (2016),Mohenjo Daro (2016),Shin Godzilla (2016),The Beatles: Eight Days a Week - The Touring Y...,The Gay Desperado (1936),"Women of '69, Unboxed"
rating,3.87247,3.40187,3.16102,2.38462,3.26786,3.88462,3.28302,3.8,3.15,3.45082,...,1,1.5,5,4.5,5,3,0,5,0,0

In [229]:
i = 1
movies_transposed.iloc[0, i]

'Jumanji (1995)'

In [221]:
pandas2arff(movies_transposed, 'movies_100000.arff')
pandas2arff(user_movies_transposed, 'user_100000.arff')

TypeError: must be str, not int